version: '2.1'

services:
    ng2admin:
        build: .
        volumes:
            - '${DIRECTORY}/ng2-admin/dist:/var/www/dist'
            - '${DIRECTORY}/docker/nginx/conf.d:/etc/nginx/conf.d:ro'
        environment:
            - VIRTUAL_HOST
            - DISCOVERY
        working_dir: /var/www
#        command: bash -c /var/www/run-prod.sh

networks:
    default:
        external:
          name: '${PROXY_NETWORK}'
